services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: mybuddy-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      APPUSER_USER: ${APPUSER_USER}
      APPUSER_PASSWORD: ${APPUSER_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Map the local DB schema files to the auto-run entrypoint directory
      - ./db-schema/:/docker-entrypoint-initdb.d/
    shm_size: 1g

volumes:
  postgres_data:
    driver: local